apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - project.yaml
  - platform-prerequisites.yaml
  - gateway-api-crds.yaml
  - aws-lbc-gateway-crds.yaml
  - platform-addons.yaml
  - platform-policies.yaml
  - platform-runtime.yaml
  - cluster-agent.yaml
