apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloudward-aws-policies
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "10"
spec:
  project: cloudward-aws-platform
  source:
    repoURL: https://github.com/biraj49/CloudWard.git
    targetRevision: main
    path: k8s/kyverno
  destination:
    server: https://kubernetes.default.svc
    namespace: kyverno
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloudward-aws-executor-guards
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "10"
spec:
  project: cloudward-aws-platform
  source:
    repoURL: https://github.com/biraj49/CloudWard.git
    targetRevision: main
    path: k8s/aws/kyverno
  destination:
    server: https://kubernetes.default.svc
    namespace: kyverno
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
