from enum import StrEnum


class EvidenceType(StrEnum):
    KUBERNETES_STATE = "KUBERNETES_STATE"
    KUBERNETES_EVENT = "KUBERNETES_EVENT"
    HEALTH_CHECK = "HEALTH_CHECK"
    METRIC = "METRIC"
    METRIC_SUMMARY = "METRIC_SUMMARY"
    LOG = "LOG"
    LOG_SUMMARY = "LOG_SUMMARY"
    TRACE = "TRACE"
    TRACE_SUMMARY = "TRACE_SUMMARY"
    DEPLOYMENT = "DEPLOYMENT"
    DEPLOYMENT_STATE = "DEPLOYMENT_STATE"
    GIT_CHANGE = "GIT_CHANGE"
    SECURITY_EVENT = "SECURITY_EVENT"
    FINOPS = "FINOPS"
