apiVersion: cilium.io/v1alpha1
kind: TracingPolicyNamespaced
metadata:
  name: cloudward-s3-privilege-attempt
  namespace: cloudward-staging
spec:
  podSelector:
    matchLabels:
      cloudward.io/demo-target: "true"
  kprobes:
    - call: sys_openat
      syscall: true
      args:
        - index: 1
          type: string
      return: true
      returnArg:
        index: 0
        type: int
      selectors:
        - matchArgs:
            - index: 1
              operator: Equal
              values:
                - /proc/1/mem

