apiVersion: v1
kind: ServiceAccount
metadata:
  name: cloudward-executor
  namespace: cloudward-staging
automountServiceAccountToken: false
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: cloudward-executor
  namespace: cloudward-staging
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch", "delete", "patch"]
  - apiGroups: [""]
    resources: ["pods/proxy"]
    verbs: ["get"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["services", "services/proxy"]
    verbs: ["get", "list"]
  - apiGroups: ["apps"]
    resources: ["deployments", "replicasets"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["cilium.io"]
    resources: ["ciliumnetworkpolicies"]
    verbs: ["get", "create", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cloudward-executor
  namespace: cloudward-staging
subjects:
  - kind: ServiceAccount
    name: cloudward-executor
    namespace: cloudward-staging
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: cloudward-executor
