serviceAccount:
  create: false
  name: karpenter

settings:
  clusterName: cloudward-aws-eu-north-1

controller:
  resources:
    requests:
      cpu: 250m
      memory: 384Mi
    limits:
      cpu: "1"
      memory: 1Gi

nodeSelector:
  cloudward.io/capacity-class: system

replicas: 1
