apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: cloudward-disallow-host-namespaces
  annotations:
    policies.kyverno.io/title: Disallow Host Namespaces
    policies.kyverno.io/category: CloudWard Baseline
    policies.kyverno.io/severity: high
spec:
  validationFailureAction: Enforce
  background: true
  rules:
    - name: require-isolated-namespaces
      match:
        any:
          - resources:
              kinds:
                - Pod
              namespaces:
                - cloudward-*
      validate:
        allowExistingViolations: false
        message: Host PID, IPC, and network namespaces are forbidden.
        pattern:
          spec:
            =(hostPID): false
            =(hostIPC): false
            =(hostNetwork): false
