{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "cloudward-demo.serviceAccountName" . }}
  labels:
    {{- include "cloudward-demo.labels" . | nindent 4 }}
automountServiceAccountToken: false
{{- end }}
