apiVersion: v1
kind: Namespace
metadata:
  name: cloudward-system
  labels:
    app.kubernetes.io/part-of: cloudward
    pod-security.kubernetes.io/enforce: restricted
---
apiVersion: v1
kind: Namespace
metadata:
  name: cloudward-ingress
  labels:
    app.kubernetes.io/part-of: cloudward
    pod-security.kubernetes.io/enforce: restricted
---
apiVersion: v1
kind: Namespace
metadata:
  name: cloudward-staging
  labels:
    app.kubernetes.io/part-of: cloudward
    cloudward.io/environment: staging
    cloudward.io/public-route: allowed
    pod-security.kubernetes.io/enforce: restricted
---
apiVersion: v1
kind: Namespace
metadata:
  name: cloudward-production
  labels:
    app.kubernetes.io/part-of: cloudward
    cloudward.io/environment: production
    cloudward.io/public-route: allowed
    pod-security.kubernetes.io/enforce: restricted
---
apiVersion: v1
kind: Namespace
metadata:
  name: observability
  labels:
    app.kubernetes.io/part-of: cloudward
    pod-security.kubernetes.io/enforce: baseline
---
apiVersion: v1
kind: Namespace
metadata:
  name: opencost
  labels:
    app.kubernetes.io/part-of: cloudward
    pod-security.kubernetes.io/enforce: restricted
---
apiVersion: v1
kind: Namespace
metadata:
  name: tetragon
  labels:
    app.kubernetes.io/part-of: cloudward
    pod-security.kubernetes.io/enforce: privileged
---
apiVersion: v1
kind: Namespace
metadata:
  name: kyverno
  labels:
    app.kubernetes.io/part-of: cloudward
    pod-security.kubernetes.io/enforce: baseline
---
apiVersion: v1
kind: Namespace
metadata:
  name: chaos-mesh
  labels:
    app.kubernetes.io/part-of: cloudward
    pod-security.kubernetes.io/enforce: privileged
