"""initial CloudWard schema

Revision ID: 4692cc9cb2ee
Revises:
Create Date: 2026-08-13 16:10:37.691855
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "4692cc9cb2ee"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "clusters",
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column(
            "environment",
            sa.Enum("LOCAL", "STAGING", "PRODUCTION", name="environment", native_enum=False),
            nullable=False,
        ),
        sa.Column("context_name", sa.String(length=255), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("labels", sa.JSON(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_clusters")),
        sa.UniqueConstraint("name", "environment", name=op.f("uq_clusters_name")),
    )
    op.create_table(
        "runbooks",
        sa.Column("runbook_id", sa.String(length=255), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("content_digest", sa.String(length=64), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("source_path", sa.String(length=1024), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_runbooks")),
        sa.UniqueConstraint("runbook_id", "version", name=op.f("uq_runbooks_runbook_id")),
    )
    op.create_table(
        "security_events",
        sa.Column("correlation_id", sa.String(length=128), nullable=False),
        sa.Column("source", sa.String(length=255), nullable=False),
        sa.Column("event_type", sa.String(length=128), nullable=False),
        sa.Column("severity", sa.String(length=16), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_security_events")),
    )
    op.create_index(
        op.f("ix_security_events_correlation_id"),
        "security_events",
        ["correlation_id"],
        unique=False,
    )
    op.create_table(
        "users",
        sa.Column("github_login", sa.String(length=255), nullable=False),
        sa.Column("display_name", sa.String(length=255), nullable=True),
        sa.Column("email", sa.String(length=320), nullable=True),
        sa.Column("avatar_url", sa.String(length=2048), nullable=True),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        sa.UniqueConstraint("github_login", name=op.f("uq_users_github_login")),
    )
    op.create_table(
        "finops_recommendations",
        sa.Column("cluster_id", sa.Uuid(), nullable=True),
        sa.Column("recommendation_type", sa.String(length=128), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("estimated_monthly_savings", sa.Float(), nullable=True),
        sa.Column("details", sa.JSON(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["cluster_id"],
            ["clusters.id"],
            name=op.f("fk_finops_recommendations_cluster_id_clusters"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_finops_recommendations")),
    )
    op.create_table(
        "oauth_identities",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("provider", sa.String(length=32), nullable=False),
        sa.Column("external_user_id", sa.String(length=255), nullable=False),
        sa.Column("provider_login", sa.String(length=255), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_oauth_identities_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_oauth_identities")),
        sa.UniqueConstraint(
            "provider", "external_user_id", name=op.f("uq_oauth_identities_provider")
        ),
    )
    op.create_index(
        op.f("ix_oauth_identities_user_id"), "oauth_identities", ["user_id"], unique=False
    )
    op.create_table(
        "role_mappings",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column(
            "role",
            sa.Enum("VIEWER", "OPERATOR", "ADMIN", name="role", native_enum=False),
            nullable=False,
        ),
        sa.Column("scope", sa.String(length=255), nullable=False),
        sa.Column("granted_by", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["granted_by"], ["users.id"], name=op.f("fk_role_mappings_granted_by_users")
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_role_mappings_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_role_mappings")),
        sa.UniqueConstraint("user_id", "scope", name=op.f("uq_role_mappings_user_id")),
    )
    op.create_index(op.f("ix_role_mappings_user_id"), "role_mappings", ["user_id"], unique=False)
    op.create_table(
        "services",
        sa.Column("cluster_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("namespace", sa.String(length=253), nullable=False),
        sa.Column("deployment_name", sa.String(length=253), nullable=False),
        sa.Column("health_url", sa.String(length=2048), nullable=True),
        sa.Column("criticality", sa.String(length=16), nullable=False),
        sa.Column("labels", sa.JSON(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["cluster_id"],
            ["clusters.id"],
            name=op.f("fk_services_cluster_id_clusters"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_services")),
        sa.UniqueConstraint("cluster_id", "namespace", "name", name=op.f("uq_services_cluster_id")),
    )
    op.create_index(op.f("ix_services_cluster_id"), "services", ["cluster_id"], unique=False)
    op.create_table(
        "incidents",
        sa.Column("correlation_id", sa.String(length=128), nullable=False),
        sa.Column("cluster_id", sa.Uuid(), nullable=True),
        sa.Column("service_id", sa.Uuid(), nullable=True),
        sa.Column("incident_type", sa.String(length=64), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("summary", sa.Text(), nullable=True),
        sa.Column(
            "environment",
            sa.Enum(
                "LOCAL", "STAGING", "PRODUCTION", name="incident_environment", native_enum=False
            ),
            nullable=False,
        ),
        sa.Column(
            "state",
            sa.Enum(
                "DETECTED",
                "COLLECTING_EVIDENCE",
                "CLASSIFYING",
                "DIAGNOSING",
                "ACTION_PROPOSED",
                "POLICY_EVALUATION",
                "AWAITING_APPROVAL",
                "EXECUTING",
                "VERIFYING",
                "ROLLBACK",
                "RESOLVED",
                "BLOCKED",
                "ESCALATED",
                name="incident_state",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("severity", sa.String(length=16), nullable=False),
        sa.Column("risk_score", sa.Integer(), nullable=True),
        sa.Column("retry_count", sa.Integer(), nullable=False),
        sa.Column("runbook_id", sa.String(length=255), nullable=True),
        sa.Column("runbook_version", sa.Integer(), nullable=True),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "retry_count >= 0 AND retry_count <= 3", name=op.f("ck_incidents_retry_count_range")
        ),
        sa.ForeignKeyConstraint(
            ["cluster_id"],
            ["clusters.id"],
            name=op.f("fk_incidents_cluster_id_clusters"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["service_id"],
            ["services.id"],
            name=op.f("fk_incidents_service_id_services"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_incidents")),
    )
    op.create_index(op.f("ix_incidents_cluster_id"), "incidents", ["cluster_id"], unique=False)
    op.create_index(
        op.f("ix_incidents_correlation_id"), "incidents", ["correlation_id"], unique=False
    )
    op.create_index(op.f("ix_incidents_service_id"), "incidents", ["service_id"], unique=False)
    op.create_index(op.f("ix_incidents_state"), "incidents", ["state"], unique=False)
    op.create_index(
        "ix_incidents_state_created_at", "incidents", ["state", "created_at"], unique=False
    )
    op.create_table(
        "action_proposals",
        sa.Column("incident_id", sa.Uuid(), nullable=False),
        sa.Column("correlation_id", sa.String(length=128), nullable=False),
        sa.Column(
            "action_type",
            sa.Enum(
                "DELETE_UNHEALTHY_POD",
                "SCALE_STAGING_DEPLOYMENT",
                "REVERT_IMAGE",
                "APPLY_QUARANTINE",
                "REMOVE_QUARANTINE",
                "CREATE_GITOPS_PR",
                "CREATE_TERRAFORM_PR",
                "CREATE_GITHUB_ISSUE",
                "REQUEST_APPROVAL",
                "NO_ACTION",
                name="action_type",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("parameters", sa.JSON(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "RUNNING",
                "SUCCEEDED",
                "FAILED",
                "REJECTED",
                "CANCELLED",
                name="proposal_status",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("risk_score", sa.Integer(), nullable=False),
        sa.Column("risk_calculation", sa.JSON(), nullable=False),
        sa.Column("proposed_by", sa.String(length=255), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "risk_score >= 0 AND risk_score <= 100",
            name=op.f("ck_action_proposals_risk_score_range"),
        ),
        sa.ForeignKeyConstraint(
            ["incident_id"],
            ["incidents.id"],
            name=op.f("fk_action_proposals_incident_id_incidents"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_action_proposals")),
    )
    op.create_index(
        op.f("ix_action_proposals_incident_id"), "action_proposals", ["incident_id"], unique=False
    )
    op.create_table(
        "audit_events",
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("actor", sa.String(length=255), nullable=False),
        sa.Column(
            "actor_type",
            sa.Enum("SYSTEM", "USER", "SERVICE", name="audit_actor_type", native_enum=False),
            nullable=False,
        ),
        sa.Column("actor_id", sa.Uuid(), nullable=True),
        sa.Column("incident_id", sa.Uuid(), nullable=True),
        sa.Column("correlation_id", sa.String(length=128), nullable=False),
        sa.Column("event_type", sa.String(length=128), nullable=False),
        sa.Column("action", sa.String(length=128), nullable=True),
        sa.Column("risk_score", sa.Integer(), nullable=True),
        sa.Column("policy_decision", sa.String(length=32), nullable=True),
        sa.Column("result", sa.String(length=32), nullable=False),
        sa.Column("metadata", sa.JSON(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["actor_id"], ["users.id"], name=op.f("fk_audit_events_actor_id_users")
        ),
        sa.ForeignKeyConstraint(
            ["incident_id"],
            ["incidents.id"],
            name=op.f("fk_audit_events_incident_id_incidents"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_events")),
    )
    op.create_index(
        op.f("ix_audit_events_correlation_id"), "audit_events", ["correlation_id"], unique=False
    )
    op.create_index(
        op.f("ix_audit_events_incident_id"), "audit_events", ["incident_id"], unique=False
    )
    op.create_index(
        "ix_audit_incident_created", "audit_events", ["incident_id", "created_at"], unique=False
    )
    op.create_table(
        "diagnoses",
        sa.Column("incident_id", sa.Uuid(), nullable=False),
        sa.Column("source", sa.String(length=32), nullable=False),
        sa.Column("classification", sa.String(length=128), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("rationale", sa.Text(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["incident_id"],
            ["incidents.id"],
            name=op.f("fk_diagnoses_incident_id_incidents"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_diagnoses")),
    )
    op.create_index(op.f("ix_diagnoses_incident_id"), "diagnoses", ["incident_id"], unique=False)
    op.create_table(
        "evidence_snapshots",
        sa.Column("incident_id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("correlation_id", sa.String(length=128), nullable=False),
        sa.Column(
            "evidence_type",
            sa.Enum(
                "KUBERNETES_STATE",
                "HEALTH_CHECK",
                "METRIC",
                "LOG",
                "TRACE",
                "DEPLOYMENT",
                "GIT_CHANGE",
                "SECURITY_EVENT",
                "FINOPS",
                name="evidence_type",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("summary", sa.Text(), nullable=False),
        sa.Column("reference", sa.String(length=2048), nullable=True),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("collected_by", sa.String(length=255), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["incident_id"],
            ["incidents.id"],
            name=op.f("fk_evidence_snapshots_incident_id_incidents"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_evidence_snapshots")),
    )
    op.create_index(
        "ix_evidence_incident_created",
        "evidence_snapshots",
        ["incident_id", "created_at"],
        unique=False,
    )
    op.create_table(
        "incident_events",
        sa.Column("incident_id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("correlation_id", sa.String(length=128), nullable=False),
        sa.Column("event_type", sa.String(length=64), nullable=False),
        sa.Column(
            "from_state",
            sa.Enum(
                "DETECTED",
                "COLLECTING_EVIDENCE",
                "CLASSIFYING",
                "DIAGNOSING",
                "ACTION_PROPOSED",
                "POLICY_EVALUATION",
                "AWAITING_APPROVAL",
                "EXECUTING",
                "VERIFYING",
                "ROLLBACK",
                "RESOLVED",
                "BLOCKED",
                "ESCALATED",
                name="incident_event_from_state",
                native_enum=False,
            ),
            nullable=True,
        ),
        sa.Column(
            "to_state",
            sa.Enum(
                "DETECTED",
                "COLLECTING_EVIDENCE",
                "CLASSIFYING",
                "DIAGNOSING",
                "ACTION_PROPOSED",
                "POLICY_EVALUATION",
                "AWAITING_APPROVAL",
                "EXECUTING",
                "VERIFYING",
                "ROLLBACK",
                "RESOLVED",
                "BLOCKED",
                "ESCALATED",
                name="incident_event_to_state",
                native_enum=False,
            ),
            nullable=True,
        ),
        sa.Column("actor", sa.String(length=255), nullable=False),
        sa.Column(
            "actor_type",
            sa.Enum("SYSTEM", "USER", "SERVICE", name="incident_actor_type", native_enum=False),
            nullable=False,
        ),
        sa.Column("details", sa.JSON(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["incident_id"],
            ["incidents.id"],
            name=op.f("fk_incident_events_incident_id_incidents"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_incident_events")),
    )
    op.create_index(
        "ix_incident_events_incident_created",
        "incident_events",
        ["incident_id", "created_at"],
        unique=False,
    )
    op.create_table(
        "model_invocations",
        sa.Column("incident_id", sa.Uuid(), nullable=True),
        sa.Column("provider", sa.String(length=64), nullable=False),
        sa.Column("model", sa.String(length=128), nullable=False),
        sa.Column("purpose", sa.String(length=128), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("input_digest", sa.String(length=64), nullable=False),
        sa.Column("usage", sa.JSON(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["incident_id"],
            ["incidents.id"],
            name=op.f("fk_model_invocations_incident_id_incidents"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_model_invocations")),
    )
    op.create_table(
        "notifications",
        sa.Column("incident_id", sa.Uuid(), nullable=True),
        sa.Column("channel", sa.String(length=64), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "RUNNING",
                "SUCCEEDED",
                "FAILED",
                "REJECTED",
                "CANCELLED",
                name="notification_status",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("destination_reference", sa.String(length=1024), nullable=True),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["incident_id"], ["incidents.id"], name=op.f("fk_notifications_incident_id_incidents")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_notifications")),
    )
    op.create_table(
        "runbook_executions",
        sa.Column("incident_id", sa.Uuid(), nullable=False),
        sa.Column("runbook_id", sa.String(length=255), nullable=False),
        sa.Column("runbook_version", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "RUNNING",
                "SUCCEEDED",
                "FAILED",
                "REJECTED",
                "CANCELLED",
                name="runbook_execution_status",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("context", sa.JSON(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["incident_id"],
            ["incidents.id"],
            name=op.f("fk_runbook_executions_incident_id_incidents"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_runbook_executions")),
    )
    op.create_index(
        op.f("ix_runbook_executions_incident_id"),
        "runbook_executions",
        ["incident_id"],
        unique=False,
    )
    op.create_table(
        "action_executions",
        sa.Column("incident_id", sa.Uuid(), nullable=False),
        sa.Column("proposal_id", sa.Uuid(), nullable=False),
        sa.Column("correlation_id", sa.String(length=128), nullable=False),
        sa.Column(
            "action_type",
            sa.Enum(
                "DELETE_UNHEALTHY_POD",
                "SCALE_STAGING_DEPLOYMENT",
                "REVERT_IMAGE",
                "APPLY_QUARANTINE",
                "REMOVE_QUARANTINE",
                "CREATE_GITOPS_PR",
                "CREATE_TERRAFORM_PR",
                "CREATE_GITHUB_ISSUE",
                "REQUEST_APPROVAL",
                "NO_ACTION",
                name="execution_action_type",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("attempt", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "RUNNING",
                "SUCCEEDED",
                "FAILED",
                "REJECTED",
                "CANCELLED",
                name="execution_status",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("result", sa.JSON(), nullable=False),
        sa.Column("error_code", sa.String(length=128), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "attempt >= 1 AND attempt <= 3", name=op.f("ck_action_executions_attempt_range")
        ),
        sa.ForeignKeyConstraint(
            ["incident_id"],
            ["incidents.id"],
            name=op.f("fk_action_executions_incident_id_incidents"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["proposal_id"],
            ["action_proposals.id"],
            name=op.f("fk_action_executions_proposal_id_action_proposals"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_action_executions")),
        sa.UniqueConstraint(
            "incident_id", "attempt", name=op.f("uq_action_executions_incident_id")
        ),
    )
    op.create_index(
        op.f("ix_action_executions_incident_id"), "action_executions", ["incident_id"], unique=False
    )
    op.create_table(
        "approvals",
        sa.Column("incident_id", sa.Uuid(), nullable=False),
        sa.Column("proposal_id", sa.Uuid(), nullable=False),
        sa.Column("actor_id", sa.Uuid(), nullable=True),
        sa.Column("decision", sa.String(length=16), nullable=False),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["actor_id"], ["users.id"], name=op.f("fk_approvals_actor_id_users")
        ),
        sa.ForeignKeyConstraint(
            ["incident_id"],
            ["incidents.id"],
            name=op.f("fk_approvals_incident_id_incidents"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["proposal_id"],
            ["action_proposals.id"],
            name=op.f("fk_approvals_proposal_id_action_proposals"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_approvals")),
    )
    op.create_index(op.f("ix_approvals_incident_id"), "approvals", ["incident_id"], unique=False)
    op.create_table(
        "policy_decisions",
        sa.Column("incident_id", sa.Uuid(), nullable=False),
        sa.Column("proposal_id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("correlation_id", sa.String(length=128), nullable=False),
        sa.Column("policy_path", sa.String(length=255), nullable=False),
        sa.Column("allowed", sa.Boolean(), nullable=False),
        sa.Column("requires_approval", sa.Boolean(), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("input_digest", sa.String(length=64), nullable=False),
        sa.Column("result", sa.JSON(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["incident_id"],
            ["incidents.id"],
            name=op.f("fk_policy_decisions_incident_id_incidents"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["proposal_id"],
            ["action_proposals.id"],
            name=op.f("fk_policy_decisions_proposal_id_action_proposals"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_policy_decisions")),
    )
    op.create_index(
        op.f("ix_policy_decisions_incident_id"), "policy_decisions", ["incident_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_policy_decisions_incident_id"), table_name="policy_decisions")
    op.drop_table("policy_decisions")
    op.drop_index(op.f("ix_approvals_incident_id"), table_name="approvals")
    op.drop_table("approvals")
    op.drop_index(op.f("ix_action_executions_incident_id"), table_name="action_executions")
    op.drop_table("action_executions")
    op.drop_index(op.f("ix_runbook_executions_incident_id"), table_name="runbook_executions")
    op.drop_table("runbook_executions")
    op.drop_table("notifications")
    op.drop_table("model_invocations")
    op.drop_index("ix_incident_events_incident_created", table_name="incident_events")
    op.drop_table("incident_events")
    op.drop_index("ix_evidence_incident_created", table_name="evidence_snapshots")
    op.drop_table("evidence_snapshots")
    op.drop_index(op.f("ix_diagnoses_incident_id"), table_name="diagnoses")
    op.drop_table("diagnoses")
    op.drop_index("ix_audit_incident_created", table_name="audit_events")
    op.drop_index(op.f("ix_audit_events_incident_id"), table_name="audit_events")
    op.drop_index(op.f("ix_audit_events_correlation_id"), table_name="audit_events")
    op.drop_table("audit_events")
    op.drop_index(op.f("ix_action_proposals_incident_id"), table_name="action_proposals")
    op.drop_table("action_proposals")
    op.drop_index("ix_incidents_state_created_at", table_name="incidents")
    op.drop_index(op.f("ix_incidents_state"), table_name="incidents")
    op.drop_index(op.f("ix_incidents_service_id"), table_name="incidents")
    op.drop_index(op.f("ix_incidents_correlation_id"), table_name="incidents")
    op.drop_index(op.f("ix_incidents_cluster_id"), table_name="incidents")
    op.drop_table("incidents")
    op.drop_index(op.f("ix_services_cluster_id"), table_name="services")
    op.drop_table("services")
    op.drop_index(op.f("ix_role_mappings_user_id"), table_name="role_mappings")
    op.drop_table("role_mappings")
    op.drop_index(op.f("ix_oauth_identities_user_id"), table_name="oauth_identities")
    op.drop_table("oauth_identities")
    op.drop_table("finops_recommendations")
    op.drop_table("users")
    op.drop_index(op.f("ix_security_events_correlation_id"), table_name="security_events")
    op.drop_table("security_events")
    op.drop_table("runbooks")
    op.drop_table("clusters")
    # ### end Alembic commands ###
